name: Mirror repo to S3
on:
  push:
    branches:
      - develop
jobs:
  s3Backup:
    if: github.repository_owner == 'bfansports'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: S3 Backup
        uses: peter-evans/s3-backup@v1
        env:
          ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          MIRROR_TARGET: bfansports-github-backup/CloudTranscode
        with:
          args: --overwrite --remove
